### ISSUE TITLE
van de cua toi la van de cua ban, ban la van de cua toi, va toi la van de cua ban, van de cua toi la cua toi, van de cua ban la cua ban

### ISSUE THREAD

**Issue by IamPierrot** [Brutal32/dotman-1.6-premium#1]
toi co rat nhieu van de

**Comment by IamPierrot** [comment]
@Brutal32 toi co van de

**Comment by CaSapChim** [comment]
roi cung co van de

**Comment by Brutal32** [comment]
pls shut the fuck up @CaSapChim @IamPierrot

**Comment by IamPierrot** [comment]
@Brutal32 vet co van de ma

**Comment by Brutal32** [comment]
@IamPierrot  vet co van de va van de la vet siu beo

**Comment by CaSapChim** [comment]
@Brutal32 ca cung co van de sieu to khong lo

**Comment by Brutal32** [comment]
xin hay dung lai van de @CaSapChim

**Comment by IamPierrot** [comment]
Vet da giai quyet xong van de
